name: flutter_photos_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  firebase_auth: ^5.1.2
  image_picker: ^1.1.2
  universal_io: ^2.2.2
  image_picker_web: ^4.0.0
  permission_handler: ^10.2.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/image/uploadImage.jpg
  uses-material-design: true
