// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6u5HpRc_UQjaqR30uzzcTdN_zs77aOF8',
    appId: '1:238371941708:web:ea9c9972687deb7085b3e9',
    messagingSenderId: '238371941708',
    projectId: 'fir-flutter-codelab-403c7',
    authDomain: 'fir-flutter-codelab-403c7.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-403c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9fphFKgGau7QcwASTiEdxg432cgqiaUo',
    appId: '1:238371941708:android:61aa1f1a13c806a485b3e9',
    messagingSenderId: '238371941708',
    projectId: 'fir-flutter-codelab-403c7',
    storageBucket: 'fir-flutter-codelab-403c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAQsOBlgs8LUn2934GwGEYl2V5QmCzDrU',
    appId: '1:238371941708:ios:9eadd6105990b8f485b3e9',
    messagingSenderId: '238371941708',
    projectId: 'fir-flutter-codelab-403c7',
    storageBucket: 'fir-flutter-codelab-403c7.appspot.com',
    iosBundleId: 'com.falconi.photosflutter',
  );
}
